on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]
  
  workflow_dispatch:
jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
    - uses: action/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      
    - run: npm i
    - run: gulp build
    
    - uses: actions/upload-artifact@v3
      with: 
        name: MyPackage
        path: dest
