name: Close stale bugs
on: 
  schedule: 
  - cron: "0 0 * * 1/1"
  workflow_dispatch: 
  
jobs: 
  stale: 
    runs-on:
      ubuntu-latest
    steps:
    - uses: actions/stale@v7.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "Ce bug est fermé pour cause d'inactivité"
        
    
    
